# Generated by Django 4.0 on 2022-11-12 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cliente', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='telefonocliente',
            name='numero',
            field=models.PositiveIntegerField(verbose_name='telefono'),
        ),
    ]
